### ISSUE TITLE
format() in the time module demands non-empty argument

### ISSUE THREAD

**Issue by dumblob** [daokoder/dao-modules#36]
The declaration of `format(self: DateTime, format = '') => string` should rather be `format(self: DateTime, format: string|none = none) => string`, otherwise calling `format()` doesn't check the length of the string and `strftime()` fails.
~~~~
0$ dao -e 'load time; io.writeln(time.now().format())'
[[Error::Param]] --- Invalid parameter(s):
Invalid format
Raised by:  invar.format(), from namespace "/usr/lib/dao/modules/libdao_time.so::time";
In code snippet:
      8 :  MOVE_PP     :     4 ,     0 ,     6 ;     1;   ().format
>>    9 :  MCALL       :     5 ,     1 ,     9 ;     1;   .format()
     10 :  MCALL       :     7 ,     2 ,    10 ;     1;   io. writeln(time. now()....
Called by:  __main__(), at instruction 9 in line 1 in file "command line codes";
~~~~

**Comment by Night-walker** [comment]
There is no need for tricky typing -- I fixed it by defaulting `format` to '%F %T'.

**Comment by dumblob** [comment]
>I fixed it by defaulting format to '%F %T'

That feels quite inconsistent with casting to `string`. Also, there shouldn't be any "trick" in making `none` default - it "just works" as expected (and as it's described in comments/documentation).

**Comment by Night-walker** [comment]
> That feels quite inconsistent with casting to string

Why? `format()` with default parameter and `(string)()` behave identically (just fixed the docs).

> Also, there shouldn't be any "trick" in making none default - it "just works" as expected (and as it's described in comments/documentation).

I still consider it needless complication.

**Comment by Night-walker** [comment]
Fixed `(string)()` to actually work as I stated.

**Comment by dumblob** [comment]
Ok, thanks.
