### ISSUE TITLE
Minor: constructor of IPv4Addr has no overload for IPv4Addr.octets

### ISSUE THREAD

**Issue by dumblob** [daokoder/dao-modules#44]
`".octets(self: IPv4Addr) => tuple<int,int,int,int>"` should be somehow compatible with the constructor for `IPv4Addr` as serializing IP to `string` and then back parsing to an IP address doesn't make much sense to me.

Unfortunately, in Dao we can't simply unfold the tuple into 4 routine arguments, so we'll probably need to add another constructor overload.

**Comment by Night-walker** [comment]
> Unfortunately, in Dao we can't simply unfold the tuple into 4 routine arguments

We can :)
```ruby
load net

ip1 = net::IPv4Addr(127,0,0,1)
ip2 = net::IPv4Addr(ip1.octets, ...)
```

**Comment by dumblob** [comment]
Hm, didn't try it with tuples, only lists. Only good news today :)
