### ISSUE TITLE
Socket may stay in bound state without exposing this information

### ISSUE THREAD

**Issue by dumblob** [daokoder/dao-modules#51]
It seems, that if the socket was properly bound, but `listen()` failed, the socket will remain bound until it's shutdown/closed. This might be inconvenient for other processes/threads as the programmer will see a socket, but the raised error would be about `listen()` and the information, that the socket is actually properly bound is not accessible.
~~~~
...
if( DaoSocket_Bind( self, Proto_TCP, ip, port, par[2]->xEnum.value ) == -1 || DaoNetwork_Listen( self->id, backlog ) == -1 ){
GetErrorMessage( errbuf, GetError() );
DaoProcess_RaiseError( proc, neterr, errbuf );
}
...
~~~~

**Comment by Night-walker** [comment]
Its state will be `$bound`, albeit that is irrelevant for the current `TcpListener` implementation.

**Comment by dumblob** [comment]
Ok, if the state is `$bound`, then there is no issue. But why would it be irrelevant for the current implementation?

**Comment by Night-walker** [comment]
Because bound&listen always come in pair in order to avoid unnecessary intermediate states.

**Comment by dumblob** [comment]
Sure, that's how I understood it and I welcome this solution. But in this case I'm pretty sure, that after catching the exception, the socket is in bound state, but this information is not visible/available and thus e.g. calling `DaoNetLib_Listen()` again will call `bind()` again which might cause issues.

**Comment by Night-walker** [comment]
> calling DaoNetLib_Listen() again will call bind() again which might cause issues.

It will close the socket first.

**Comment by dumblob** [comment]
Oh, now I see - `DaoSocket_Delete()` does it.
