### ISSUE TITLE
Avoid *(int*)ip in net/dao_network.c due to length of int

### ISSUE THREAD

**Issue by dumblob** [daokoder/dao-modules#53]
On many places in *net/dao_network.c* casting from `uchar_t[4]` to `int` is used for the `s_addr` field value, but `s_addr` is at least 32b and `int` is only guaranteed to be at least `16b`. The casting:
~~~~
addr.sin_addr.s_addr = *(int*)ip;
~~~~
should be thus to `unsigned long`:
~~~~
addr.sin_addr.s_addr = *(unsigned long*)ip;
~~~~

**Comment by Night-walker** [comment]
Thanks again, I refactored that.

**Comment by dumblob** [comment]
Thanks. Maybe just as preparation for other IP protocols, rename `ipaddr_t` to `ipv4addr_t` :wink:.

**Comment by Night-walker** [comment]
Done.

**Comment by dumblob** [comment]
Well done. There is one minor typo:
~~~~ruby
static int DaoSocket_Bind( DaoSocket *self, socket_proto proto, ipv4_t ip, int port, socket_opts opts )
~~~~
should also use `port_t`:
~~~~ruby
static int DaoSocket_Bind( DaoSocket *self, socket_proto proto, ipv4_t ip, port_t port, socket_opts opts )
~~~~

**Comment by Night-walker** [comment]
Done.

**Comment by dumblob** [comment]
Thanks.
