### ISSUE TITLE
Enhancement: support for http-equiv="Expires" in the web.html module

### ISSUE THREAD

**Issue by dumblob** [daokoder/dao-modules#55]
[Expires](http://www.i18nguy.com/markup/metatags.html#expires) is a useful meta tag:

~~~~
<META HTTP-EQUIV="EXPIRES" CONTENT="Mon, 22 Jul 2002 11:12:01 GMT">
~~~~

**Comment by Night-walker** [comment]
It's not in the html 5 spec, and stackoverflow suggests that the corresponding http header should be used instead.

**Comment by dumblob** [comment]
Both is true. It's a poor, but very handy solution in cases, when you can't construct http header (which is surprisingly often). Yes, it undermines the idea of caching on the pathway (because cache servers usually don't support deep content inspection), but if there is no other option...

But I agree, that we should leave the `web.html` module HTML5-compliant and thus I'm closing this ticket.

As a solution, one can use `text('<META HTTP-EQUIV="EXPIRES" CONTENT="Mon, 22 Jul 2002 11:12:01 GMT">')` instead.
