### ISSUE TITLE
Minor: possible memory leaks

### ISSUE THREAD

**Issue by dumblob** [daokoder/dao-modules#61]
If I didn't miss anything, `DaoProcess_RaiseError()` calls e.g. in `PIPE_New()` are not accompanied by any `stream` free/GC_decrement. The same holds for `self` in `DaoIO_Open()`.

**Comment by Night-walker** [comment]
Fixed `DaoIO_Open()`. `PIPE_New()` is OK, because the value is handed to the `DaoProcess` first.
