### ISSUE TITLE
default umask (file/dir mode)

### ISSUE THREAD

**Issue by dumblob** [daokoder/dao-modules#64]
Currently `s_IRWXU|S_IRGRP|S_IXGRP|S_IXOTH` permissions are used in `FS_Mkdir()`, but this feels inconsistent:

1. default configuration on most Linux/UNIX distributions (umask 022 is the most common) - but I personally don't like 022, because it's not secure

2. it doesn't make much sense to me - either we should fully obey global umask setting or we should set group permissions to *rwx* (S_IRWXG) just like user permissions (this is secure and is used also on production servers)

**Comment by Night-walker** [comment]
Changed the group part to `S_IRWXG`.

**Comment by dumblob** [comment]
Fixed.
