### ISSUE TITLE
Bug: incorrect \uN... conversion in the JSON module

### ISSUE THREAD

**Issue by dumblob** [daokoder/dao-modules#80]
It seems, that the conversion of http://python-conflab.rhcloud.com/oa2015/export/m_app/ using `.parse()` somehow doesn't work well (the outcome is not 1:1 copy of the original text), even though https://github.com/daokoder/dao-modules/blob/master/web/json/dao_json.c#L267 looks correct. Any ideas what am I missing?

**Comment by dumblob** [comment]
You can check the expected results with `jshon` (`jshon < m_app-export.json > out_utf-8.json`).

**Comment by Night-walker** [comment]
Fixed.

**Comment by dumblob** [comment]
Thanks, forgot to close it after testing it on other JSON inputs.
